# Generated by Django 4.2.4 on 2023-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_status',
            field=models.CharField(choices=[('Home', 'Home'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
