# Generated by Django 4.2.4 on 2023-08-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_store_name_ar_store_name_en_storecategory_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name_af',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ar_dz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ast',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_be',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_bn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_bs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_cs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_cy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_da',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_dsb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_el',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en_au',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_eo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es_co',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es_ni',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_es_ve',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_et',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_eu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_fy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ga',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_gd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_gl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_hr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_hsb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_hu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_hy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_io',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_is',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_kab',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_kk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_km',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_kn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_lb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_lt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_lv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_mk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ml',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_mn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_mr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_my',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_nb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_nn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_os',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sq',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sr_latn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_sw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_te',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_tg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_th',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_tk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_tt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_udm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_ur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_vi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_af',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ar_dz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ast',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_be',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_bn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_bs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ckb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_cs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_cy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_da',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_dsb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_el',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_en_au',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_eo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es_co',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es_ni',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_es_ve',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_et',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_eu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_fy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ga',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_gd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_gl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_hr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_hsb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_hu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_hy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_io',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_is',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ja',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_kab',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_kk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_km',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_kn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_lb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_lt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_lv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_mk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ml',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_mn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_mr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_my',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_nb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_nn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_os',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_pa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_pl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sq',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sr_latn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_sw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_te',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_tg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_th',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_tk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_tt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_udm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_vi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
