# Generated by Django 4.2.4 on 2023-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_store_name_af_remove_store_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
