# Generated by Django 4.2.7 on 2023-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_store_name_ar_store_name_en_storecategory_name_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/brand-images"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/product-images"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/productcategory-images"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/store-images"
            ),
        ),
        migrations.AlterField(
            model_name="storecategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/storecategory-images"
            ),
        ),
    ]
