# Generated by Django 4.2.4 on 2023-08-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address_address_status'),
        ('cart', '0006_order_total_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.address'),
        ),
    ]
