# Generated by Django 4.2.7 on 2023-12-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_address_options"),
        ("cart", "0007_order_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.address"
            ),
        ),
    ]
